version: '3.2'
services:
  sourced-ui:
    user: 0:0
    volumes:
      - ${SOURCED_UI_ABS_PATH}/superset/superset:/home/superset/superset
      - ${SOURCED_UI_ABS_PATH}/superset/dashboards:/home/superset/dashboards
      - ${SOURCED_UI_ABS_PATH}/superset/contrib/docker/superset_config.py:/home/superset/superset/superset_config.py
      - ${SOURCED_UI_ABS_PATH}/superset/contrib/docker/bootstrap.py:/home/superset/bootstrap.py
      - ${SOURCED_UI_ABS_PATH}/superset/contrib/docker/docker-entrypoint.sh:/entrypoint.sh
    environment:
      SUPERSET_ENV: development
      LOCAL_USER: ${LOCAL_USER:-}
